# **Create a 2x3 matrix**

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:")
print(A)

Matrix A:
[[1 2 3]
 [4 5 6]]


In [3]:
# 3x3 Zero Matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:")
print(zero_matrix)

# 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)

Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Define Two Matrices Of The Same Shape**

In [4]:
B = np.array([[1, 2], [3, 4]])
C = np.array([[5, 6], [7, 8]])

# Matrix Addition
addition_result = B + C
print("B + C:")
print(addition_result)

# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 6  8]
 [10 12]]
B - C:
[[-4 -4]
 [-4 -4]]


# **Exercise 1**

In [5]:
B = np.array([[5, 6], [8, 7]])
C = np.array([[2, 1], [4, 2]])


addition_result = B + C
print("B + C:")
print(addition_result)

# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 7  7]
 [12  9]]
B - C:
[[3 5]
 [4 5]]


# **Defining Matrices for Multiplication**

In [6]:
D = np.array([[1, 2], [3, 4]])
E = np.array([[2, 0], [1, 2]])

# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)

D * E (Matrix Multiplication):
[[ 4  4]
 [10  8]]


## **Exercise 2**

In [7]:
# Define matrices for multiplication
D = np.array([[3, 7, 1], [2, 1,9]])
E = np.array([[5, 2], [1, 2],[6,4]])

# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)

D * E (Matrix Multiplication):
[[28 24]
 [65 42]]


## **Defining Matrices for Multiplication**

In [8]:
D = np.array([[3, 7, 1], [2, 1, 9]])
E = np.array([[5, 2, 1], [6, 4, 1]])  # Define E directly in the shape (2, 3)

# Element-wise Multiplication
elementwise_result = D * E
print("D * E (Element-wise Multiplication):")
print(elementwise_result)

D * E (Element-wise Multiplication):
[[15 14  1]
 [12  4  9]]


# **Transpose of a Matrix**

In [9]:
transpose_result = D.T
print("Transpose of D:")
print(transpose_result)

Transpose of D:
[[3 2]
 [7 1]
 [1 9]]


# **Exercise 3: Matrix Transpose**

In [10]:
d = np.array([[1, 2, 3], [4, 5, 6]])


transpose_matrix = d.T
print("Original Matrix (2x3):")
print(d)
print("\nTranspose of the Matrix (3x2):")
print(transpose_matrix)

Original Matrix (2x3):
[[1 2 3]
 [4 5 6]]

Transpose of the Matrix (3x2):
[[1 4]
 [2 5]
 [3 6]]


## **Define a 2x2 Square Matrix**

In [11]:
F = np.array([[4, 2], [3, 1]])

# Determinant of F
determinant_result = np.linalg.det(F)
print("Determinant of F:", determinant_result)

Determinant of F: -2.0


# **Exercise 4: Calculating the Determinant**

In [12]:
F = np.array([[9, 8, 3], [2, 1, 6],[8,6,7]])

determinant_result = np.linalg.det(F)
print("Determinant of F:", determinant_result)

Determinant of F: 22.99999999999998


## **Matrix Inverse**

In [13]:
# Define an invertible 2x2 matrix
G = np.array([[4, 7], [2, 6]])

# Inverse of G
inverse_result = np.linalg.inv(G)
print("Inverse of G:")
print(inverse_result)

Inverse of G:
[[ 0.6 -0.7]
 [-0.2  0.4]]


# **Exercise 5: Finding the Inverse**

In [14]:
matrix = np.array([[4, 7, 2],
                   [3, 6, 1],
                   [2, 5, 9]])

# Calculate the inverse of the matrix
inverse_result = np.linalg.inv(matrix)

# Print the inverse
print("Inverse of the matrix:")
print(inverse_result)

Inverse of the matrix:
[[ 1.81481481 -1.96296296 -0.18518519]
 [-0.92592593  1.18518519  0.07407407]
 [ 0.11111111 -0.22222222  0.11111111]]


# **Additional Challenge**

In [15]:
A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

B = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]


result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]


for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]


print("Result of matrix multiplication:")
for row in result:
    print(row)

Result of matrix multiplication:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


# **Generating a Random 10×1010 \times 1010×10 Matrix and Performing Basic Operations**

In [16]:
# Generate a random 10x10 matrix
random_matrix_A = np.random.rand(10, 10)
print("Random 10x10 Matrix A:")
print(random_matrix_A)

Random 10x10 Matrix A:
[[0.66274181 0.78176632 0.87116509 0.89044775 0.35051077 0.20179185
  0.00756648 0.44400337 0.14725903 0.40480957]
 [0.72132195 0.16456419 0.55417064 0.9908704  0.75875332 0.76074568
  0.90130572 0.16250788 0.857479   0.81075644]
 [0.46942472 0.52489316 0.63545318 0.88417099 0.85996137 0.3402342
  0.51259648 0.49075713 0.72671635 0.90468657]
 [0.61055932 0.48745594 0.69609115 0.0765469  0.13292868 0.06039129
  0.90013787 0.99620124 0.96547912 0.66891391]
 [0.38049602 0.68849058 0.9659428  0.52087051 0.5884536  0.64789912
  0.34343697 0.83144422 0.784666   0.5208126 ]
 [0.28383622 0.782474   0.2096333  0.38186246 0.14222569 0.52693446
  0.36410058 0.52629761 0.33116202 0.17075939]
 [0.37547979 0.36422836 0.28597639 0.7709788  0.67139911 0.97078428
  0.02965234 0.38148744 0.50361008 0.12814617]
 [0.88493728 0.61047794 0.46313278 0.62177462 0.69273578 0.81539431
  0.47282921 0.02600966 0.05469635 0.61170221]
 [0.26934694 0.69645181 0.4827686  0.86318463 0.9597258  0

# **Creating Another Random Matrix of the Same Size**

## **Generate a Second Random 10x10 Matrix**

In [17]:
random_matrix_B = np.random.rand(10, 10)
print("\nRandom 10x10 Matrix B:")
print(random_matrix_B)


Random 10x10 Matrix B:
[[0.94031894 0.33178271 0.76468781 0.69194852 0.71418233 0.54042818
  0.15871545 0.70729523 0.95449885 0.4644758 ]
 [0.6914506  0.17887977 0.74129824 0.36512112 0.20886015 0.50766579
  0.93689678 0.442623   0.87756727 0.90875042]
 [0.40555755 0.47038685 0.46525186 0.62986414 0.14284381 0.09800895
  0.14909499 0.26298584 0.02115119 0.46936631]
 [0.571441   0.94237848 0.07814449 0.52384081 0.9658746  0.81802326
  0.52823606 0.30477427 0.07565057 0.98524387]
 [0.36690562 0.42358656 0.3168151  0.40202757 0.72191242 0.3523504
  0.80369896 0.60079747 0.82235217 0.12061443]
 [0.89138706 0.24875529 0.63572686 0.43470572 0.4099236  0.76516123
  0.547527   0.49657554 0.34622205 0.45849679]
 [0.9083403  0.24749866 0.40506101 0.26644844 0.26332027 0.55970613
  0.94579475 0.56402036 0.06502413 0.54346654]
 [0.16814323 0.22590074 0.55447526 0.17780864 0.55911463 0.11545543
  0.86245302 0.7501782  0.64361239 0.06348583]
 [0.94617999 0.88552449 0.02887315 0.11813253 0.78480634 

## **Matrix Addition**

In [18]:
addition_result = random_matrix_A + random_matrix_B
print("\nA + B (Matrix Addition):")
print(addition_result)


A + B (Matrix Addition):
[[1.60306075 1.11354903 1.6358529  1.58239627 1.06469309 0.74222003
  0.16628193 1.1512986  1.10175788 0.86928537]
 [1.41277254 0.34344396 1.29546888 1.35599152 0.96761348 1.26841147
  1.83820251 0.60513088 1.73504627 1.71950686]
 [0.87498227 0.99528001 1.10070503 1.51403513 1.00280517 0.43824315
  0.66169147 0.75374297 0.74786755 1.37405288]
 [1.18200032 1.42983442 0.77423564 0.60038771 1.09880327 0.87841455
  1.42837393 1.30097551 1.04112969 1.65415778]
 [0.74740163 1.11207713 1.28275791 0.92289808 1.31036602 1.00024952
  1.14713593 1.43224169 1.60701816 0.64142703]
 [1.17522328 1.03122928 0.84536016 0.81656818 0.55214929 1.29209569
  0.91162757 1.02287315 0.67738406 0.62925618]
 [1.28382009 0.61172702 0.6910374  1.03742724 0.93471937 1.53049041
  0.9754471  0.9455078  0.56863422 0.67161271]
 [1.05308052 0.83637868 1.01760804 0.79958326 1.25185041 0.93084974
  1.33528223 0.77618786 0.69830874 0.67518803]
 [1.21552693 1.5819763  0.51164176 0.98131716 1.744532

## **Matrix Subtraction**

In [19]:
subtraction_result = random_matrix_A - random_matrix_B
print("\nA - B (Matrix Subtraction):")
print(subtraction_result)


A - B (Matrix Subtraction):
[[-0.27757713  0.44998361  0.10647728  0.19849923 -0.36367156 -0.33863634
  -0.15114897 -0.26329186 -0.80723982 -0.05966623]
 [ 0.02987135 -0.01431559 -0.1871276   0.62574928  0.54989317  0.2530799
  -0.03559106 -0.28011513 -0.02008828 -0.09799399]
 [ 0.06386717  0.05450632  0.17020132  0.25430685  0.71711756  0.24222525
   0.36350149  0.22777129  0.70556516  0.43532026]
 [ 0.03911832 -0.45492255  0.61794666 -0.44729391 -0.83294592 -0.75763196
   0.37190181  0.69142698  0.88982855 -0.31632996]
 [ 0.0135904   0.26490402  0.6491277   0.11884294 -0.13345882  0.29554872
  -0.460262    0.23064675 -0.03768617  0.40019817]
 [-0.60755084  0.53371871 -0.42609357 -0.05284326 -0.2676979  -0.23822677
  -0.18342642  0.02972207 -0.01506003 -0.2877374 ]
 [-0.53286051  0.1167297  -0.11908461  0.50453037  0.40807884  0.41107815
  -0.91614241 -0.18253293  0.43858595 -0.41532036]
 [ 0.71679405  0.3845772  -0.09134248  0.44396598  0.13362115  0.69993888
  -0.38962381 -0.724168

## **Matrix Multiplication**

In [20]:
multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print("\nA * B (Matrix Multiplication):")
print(multiplication_result)


A * B (Matrix Multiplication):
[[2.8297835  2.30654793 2.38013843 2.3405663  2.34272542 2.43725191
  2.55331781 2.06867051 2.18494973 2.68812607]
 [4.74676909 3.52700207 2.86590063 2.94287259 3.48666237 4.29371313
  3.99559358 2.75966891 2.74892167 3.49119621]
 [4.03543664 3.30785749 2.83104671 2.75170202 3.17446302 3.76967398
  3.96538197 2.61737603 2.82519054 3.19779849]
 [3.69215479 2.50406907 2.72228203 2.11006091 2.41681898 2.96053708
  3.65677564 2.4623915  2.73563473 2.59113662]
 [3.86409875 2.91578269 2.93208916 2.57346892 2.94393986 3.29650361
  3.88273719 2.67212813 3.00354395 3.07410005]
 [2.4814287  1.49866976 1.89092973 1.4374332  1.74208642 2.07160762
  2.56063427 1.7362246  1.95219285 2.08834073]
 [2.92764756 2.20057516 1.92159364 1.88447475 2.63508035 2.67125016
  2.73751795 2.00268106 2.3323195  2.35593282]
 [3.67886495 2.27714537 2.83142749 2.60706791 2.47284933 3.1337567
  2.95649398 2.45760105 2.39146991 2.72090783]
 [3.82773331 3.01585133 2.50631515 2.43980851 3.1

In [21]:
# Transpose of random_matrix_A
transpose_result_A = random_matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_result_A)

# Transpose of random_matrix_B
transpose_result_B = random_matrix_B.T
print("\nTranspose of Matrix B:")
print(transpose_result_B)


Transpose of Matrix A:
[[0.66274181 0.72132195 0.46942472 0.61055932 0.38049602 0.28383622
  0.37547979 0.88493728 0.26934694 0.72843684]
 [0.78176632 0.16456419 0.52489316 0.48745594 0.68849058 0.782474
  0.36422836 0.61047794 0.69645181 0.04302396]
 [0.87116509 0.55417064 0.63545318 0.69609115 0.9659428  0.2096333
  0.28597639 0.46313278 0.4827686  0.27235157]
 [0.89044775 0.9908704  0.88417099 0.0765469  0.52087051 0.38186246
  0.7709788  0.62177462 0.86318463 0.3178864 ]
 [0.35051077 0.75875332 0.85996137 0.13292868 0.5884536  0.14222569
  0.67139911 0.69273578 0.9597258  0.00825693]
 [0.20179185 0.76074568 0.3402342  0.06039129 0.64789912 0.52693446
  0.97078428 0.81539431 0.78351277 0.1428509 ]
 [0.00756648 0.90130572 0.51259648 0.90013787 0.34343697 0.36410058
  0.02965234 0.47282921 0.23460802 0.8940877 ]
 [0.44400337 0.16250788 0.49075713 0.99620124 0.83144422 0.52629761
  0.38148744 0.02600966 0.34133228 0.08090378]
 [0.14725903 0.857479   0.72671635 0.96547912 0.784666   0.

# **Learning Assessment Questions**

## **1. Matrix Creation and Structure**

  A matrix is a rectangular array of numbers, symbols, or expressions arranged in rows and columns. Matrices are fundamental in linear algebra and are used in various fields such as physics, computer graphics, and machine learning. The size of a matrix is defined by the number of its rows and columns.


Sample Code:

In [22]:
k_3x23 = np.random.randint(1, 10,(3, 23))


k_23x2 = np.random.randint(1, 10,(23, 2))

print("3x23 Matrix:\n", k_3x23)
print("\n23x2 Matrix:\n", k_23x2)

3x23 Matrix:
 [[1 4 8 8 1 9 7 6 1 4 3 5 4 4 5 2 9 4 4 4 1 8 1]
 [6 9 4 9 9 5 9 6 2 2 2 1 8 2 5 8 4 8 1 3 7 5 2]
 [8 4 2 5 7 4 1 3 3 2 4 5 9 3 2 1 7 1 4 9 5 3 7]]

23x2 Matrix:
 [[5 6]
 [4 8]
 [6 5]
 [6 2]
 [4 2]
 [3 2]
 [4 5]
 [5 2]
 [7 9]
 [2 1]
 [6 9]
 [4 4]
 [2 7]
 [2 2]
 [4 8]
 [5 2]
 [9 1]
 [5 9]
 [6 4]
 [9 1]
 [2 6]
 [6 2]
 [1 8]]


## **2. Basic Matrix Operations**
  For matrix addition, two matrices must have the same dimensions (same number of rows and columns). You add them by adding each matching element.

  For matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second. The result will have the same number of rows as the first matrix and the same number of columns as the second. Each element in the result is a dot product of a row from the first matrix and a column from the second.

Sample Code:

In [23]:
A = np.random.randint(1, 10,(5, 5))
B = np.random.randint(1, 10,(5, 5))


matrix_sum = A + B


matrix_product = np.dot(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix Addition (A + B):\n", matrix_sum)
print("\nMatrix Multiplication (A * B):\n", matrix_product)

Matrix A:
 [[6 8 8 9 4]
 [2 5 7 9 7]
 [2 9 1 9 9]
 [2 1 4 4 7]
 [8 2 1 3 2]]

Matrix B:
 [[5 2 1 3 5]
 [8 8 8 6 5]
 [7 9 5 5 7]
 [8 7 7 6 8]
 [1 7 5 5 6]]

Matrix Addition (A + B):
 [[11 10  9 12  9]
 [10 13 15 15 12]
 [ 9 18  6 14 16]
 [10  8 11 10 15]
 [ 9  9  6  8  8]]

Matrix Multiplication (A * B):
 [[226 239 193 180 222]
 [178 219 175 160 198]
 [170 211 187 164 188]
 [ 85 125  93  91 117]
 [ 89  76  60  69  93]]


## **3. Matrix Transposition**
  The transpose of a matrix is obtained by flipping it over its diagonal, which swaps its rows and columns. If a matrix has dimensions 𝑚 × 𝑛 m×n, its transpose will have dimensions 𝑛 × 𝑚

Sample Code:

In [24]:
k = np.random.randint(1, 10, (3, 2))


matrix_transpose = k.T

print("Original 3x2 Matrix:\n", matrix)
print("\nTranspose of the Matrix (2x3):\n", matrix_transpose)

Original 3x2 Matrix:
 [[4 7 2]
 [3 6 1]
 [2 5 9]]

Transpose of the Matrix (2x3):
 [[9 9 9]
 [1 4 9]]


## **4. Working with Large Matrices**

In [25]:
matrix = np.random.randint(1, 11, (5, 5))

matrix_sum = np.sum(matrix)


matrix_transpose = matrix.T

# Print the results
print("Original 5x5 Matrix:\n", matrix)
print("\nSum of all elements in the matrix:", matrix_sum)
print("\nTranspose of the Matrix:\n", matrix_transpose)

Original 5x5 Matrix:
 [[ 8  4 10  7  9]
 [ 7  8  4  2  3]
 [ 7  8  3  5  4]
 [ 5  6 10 10  1]
 [ 7  6  3  1  8]]

Sum of all elements in the matrix: 146

Transpose of the Matrix:
 [[ 8  7  7  5  7]
 [ 4  8  8  6  6]
 [10  4  3 10  3]
 [ 7  2  5 10  1]
 [ 9  3  4  1  8]]


## **Answer:**

  If we want to make a random 5 × 5 5x5 matrix in NumPy, we can just write np.random.randint(1, 11, (5, 5)) because we want to generate a whole number between 1 and 10 for each element in the matrix. Next we can compute the sum of all elements of the matrix using np.sum(matrix). Finally, to get the transpose of the matrix we are using matrix.T, which flips the matrix across the diagonal, making rows into columns. This gives us the total of the matrix elements and it’s transposed form.

## **Applying Matrix Operations in Context**

  Matrix Addition (D + E): Adds matching elements from both matrices. This can help in tasks like merging two images or increasing brightness.

  Matrix Subtraction (D - E): Finds differences between two matrices. This is useful in detecting changes between images or video frames, such as movement.

  Matrix Multiplication (D * E): Combines matrices in a way that’s essential for tasks in graphics (e.g., rotating objects) and machine learning calculations.

In [26]:
D = np.random.randint(1, 11, (10, 10))
E = np.random.randint(1, 11, (10, 10))


matrix_addition = D + E
print("Matrix Addition (D + E):\n", matrix_addition)


matrix_subtraction = D - E
print("\nMatrix Subtraction (D - E):\n", matrix_subtraction)


matrix_multiplication = np.dot(D, E)
print("\nMatrix Multiplication (D * E):\n", matrix_multiplication)

Matrix Addition (D + E):
 [[ 8 10 13 15 11 11 11 12  6 14]
 [15 10  8 14 13 11 13  9  3  7]
 [ 6 10 15  7 16 18 11 11  9 13]
 [ 5  8 14 13 10  5  9 11  4 11]
 [ 8 20  7  8 10 13 10 15 16  8]
 [13 12  5  8 10 14  5  6  6 10]
 [14 14 16  7 12 11 15 10  3  7]
 [10 11 18 12 13 15 19  8  6 17]
 [ 9  8  8 10 11 11  7 16 11  8]
 [17 16  9 19  6  7  5  7 15  9]]

Matrix Subtraction (D - E):
 [[-6  2 -1 -3 -3  1 -5  0 -4  0]
 [-1  2  6 -2  5  5 -3  3 -1 -5]
 [ 4  0  3 -5  2  2  3  3 -5 -3]
 [ 1  6  6 -1 -2  1  3  5  0  1]
 [-4  0  3 -2 -8 -1  8  5 -4  4]
 [ 1 -8 -3 -6 -4 -4  1  4  0 -4]
 [ 0  0  4 -1  2  7 -3  6  1 -5]
 [ 8  5  0 -8  3  1 -1 -6 -4  3]
 [-5  6  6 -4  3  7 -3 -2 -5  6]
 [-3  0  5  1  0 -3 -1 -5 -5  1]]

Matrix Multiplication (D * E):
 [[237 260 192 339 257 250 227 191 240 260]
 [276 325 258 392 357 315 288 226 275 322]
 [320 388 273 418 368 359 306 250 328 343]
 [265 282 254 398 308 285 310 242 282 320]
 [322 293 254 428 295 277 367 260 266 327]
 [193 185 159 252 193 179 193 161 